name: Excelify JSON - Build, Test & Lint Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: '10'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run linting
      run: |
        pnpm lint
        pnpm lint:fix

    - name: Run format
      run: pnpm format

    - name: Run tests
      run: pnpm test

  docker-build:
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t excelify-json .

    - name: Test Docker image
      run: |
        # Run the container in detached mode, mapping port 3000
        docker run -d --name excelify-container -p 3000:3000 excelify-json

        # Check if the container is running
        if [ "$(docker ps -q -f name=excelify-container)" ]; then
          echo "Container is running"
        else
          echo "Container failed to start"
          exit 1
        fi

        # Wait for the container to start (up to 30 seconds)
        for i in {1..6}; do
          if curl --fail http://localhost:3000; then
            echo "Container is responding on port 3000"
            break
          else
            echo "Waiting for container to respond..."
            sleep 5
          fi

          if [ $i -eq 6 ]; then
            echo "Container did not respond in time"
            docker logs excelify-container
            docker stop excelify-container
            exit 1
          fi
        done

        # Clean up the container
        docker logs excelify-container
        docker stop excelify-container
